app:
  name: "Zengine Dojo Boilerplate"
  version: "0.0.1"
  port: 5000
  domain: "http://localhost:5000"
  environment: "development"

auth:


view:
  path: "./views"

assets:
  path: "./assets/dist"

session:
  name: "zengine_dojo"
  secret: "secret"