apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: web
    newName: ghcr.io/zenginedev/dojo-boilerplate
    newTag: v0.0.1

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: dojo
    path: ingress_patch.yaml